services:
  # mongo:
  #   image: mongo:7.0
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #     MONGO_INITDB_DATABASE: camshop_micro_product
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ../db/mongodb:/data/db
  # mongo-express:
  #   image: mongo-express:1.0.2-20-alpine3.19
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  postgres:
    image: postgres:15-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camshop_micro_user
    ports:
      - 5432:5432
    volumes:
      - ../db/postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
  api-gateway:
    container_name: api-gateway
    image: reg.findurjob.uk/camshop/api-gateway:1.0.0
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      # target: development
    # command: sh -c "npm run start:dev"
    ports:
      - 3001:3001
  mail-service:
    container_name: mail-service
    image: reg.findurjob.uk/camshop/mail-service:1.0.0
    build:
      context: .
      dockerfile: apps/mail/Dockerfile
      # target: development
    # command: sh -c "npm run start:dev mail"
    ports:
      - 3004:3004
  users-service:
    container_name: users-service
    image: reg.findurjob.uk/camshop/users-service:1.0.0
    build:
      context: .
      dockerfile: apps/users/Dockerfile
      # target: development
    # command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev users"
    ports:
      - 3003:3003
    depends_on:
      - postgres
