services:
  mongo:
    container_name: mongo
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: camshop_micro_product
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  postgres:
    container_name: postgres
    image: postgres:17.6-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh

  # rabbitmq:
  #   image: rabbitmq:3.9.10-management-alpine
  #   ports:
  #     - 5672:5672
  
  redis:
    container_name: redis
    image: redis:7.2.6-alpine
    ports:
      - 6379:6379  
  # ------------------------------------SERVICES--------------------------------------------
  
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      # target: development
    ports:
      - 3001:3001

  products-service:
    container_name: products-service
    build:
      context: .
      dockerfile: apps/products/Dockerfile
      # target: development
    ports:
      - 3002:3002
    depends_on:
      - mongo
  
  # mail-service:
  #   container_name: mail-service
  #   # image: reg.findurjob.uk/camshop/mail-service:0.0.1
  #   build:
  #     context: .
  #     dockerfile: apps/mail/Dockerfile
  #     # target: development
  #   # command: sh -c "npm run start:dev mail"
  #   ports:
  #     - 3004:3004

  users-service:
    container_name: users-service
    build:
      context: .
      dockerfile: apps/users/Dockerfile
      # target: development
    ports:
      - 3003:3003
    depends_on:
      - postgres

  # orders-service:
  #   container_name: orders-service
  #   build:
  #     context: .
  #     dockerfile: apps/orders/Dockerfile
  #   depends_on:
  #     - postgres
volumes:
  postgres:
  mongo_data: