// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v3.20.3
// source: proto/orders/orders.proto

/* eslint-disable */
import { Empty } from '@app/common/interfaces';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { UpdateOrderDto } from './update-order.dto';
import { CreateOrderDto } from './create-order.dto';
import { Order, Orders } from './order.dto';

export const protobufPackage = 'orders';

export interface FindOneOrderDto {
	id: string;
}

export interface FindAllOrderByUserDto {
	user_id: string;
}

export interface FindOneOrderByUserDto {
	id: string;
	user_id: string;
}

export interface RemoveOrderDto {
	id: string;
}

export interface PermanentlyRemoveOrderDto {
	id: string;
}

export const ORDERS_PACKAGE_NAME = 'orders';

export interface OrdersServiceClient {
	findOne(request: FindOneOrderDto): Observable<Order>;

	findAll(request: Empty): Observable<Orders>;

	findAllByUser(request: FindAllOrderByUserDto): Observable<Orders>;

	findOneByUser(request: FindOneOrderByUserDto): Observable<Order>;

	create(request: CreateOrderDto): Observable<Order>;

	update(request: UpdateOrderDto): Observable<Order>;

	remove(request: RemoveOrderDto): Observable<Empty>;

	permanentlyRemove(request: PermanentlyRemoveOrderDto): Observable<Empty>;
}

export interface OrdersServiceController {
	findOne(
		request: FindOneOrderDto,
	): Promise<Order> | Observable<Order> | Order;

	findAll(
		request: Empty,
	): Promise<Orders> | Observable<Orders> | Orders;

	findAllByUser(
		request: FindAllOrderByUserDto,
	): Promise<Orders> | Observable<Orders> | Orders;

	findOneByUser(
		request: FindOneOrderByUserDto,
	): Promise<Order> | Observable<Order> | Order;

	create(
		request: CreateOrderDto,
	): Promise<Order> | Observable<Order> | Order;

	update(
		request: UpdateOrderDto,
	): Promise<Order> | Observable<Order> | Order;

	remove(request: RemoveOrderDto): Promise<Empty> | Observable<Empty> | Empty;

	permanentlyRemove(
		request: PermanentlyRemoveOrderDto,
	): Promise<Empty> | Observable<Empty> | Empty;
}

export function OrdersServiceControllerMethods() {
	return function (constructor: Function) {
		const grpcMethods: string[] = [
			'findOne', 'findAll', 'findAllByUser',
			'findOneByUser', 'create', 'update', 'remove',
			'permanentlyRemove',
		];
		for (const method of grpcMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcMethod('OrdersService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
		const grpcStreamMethods: string[] = [];
		for (const method of grpcStreamMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcStreamMethod('OrdersService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
	};
}

export const ORDERS_SERVICE_NAME = 'OrdersService';
