// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v3.20.3
// source: proto/products/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Category } from '../categories';
import { Manufacturer } from '../manufacturers';
import { Empty } from '@app/common/interfaces';

export const protobufPackage = 'products';

export interface CreateProductDto {
	name: string;
	description?: string | undefined;
	price?: number | undefined;
	stock?: number | undefined;
	original_price: number;
	category_id: string;
	tags: string[];
	manufacturer_id: string;
	image_url?: string | undefined;
}

export interface FindOneProductDto {
	id: string;
}

export interface UpdateProductDto {
	id: string;
	name: string;
	description: string;
	price: number;
	stock: number;
	original_price: number;
	category_id: string;
	tags: string[];
	manufacturer_id: string;
	image_url: string;
}

export interface RemoveProductDto {
	id: string;
}

export interface PermanentlyRemoveProductDto {
	id: string;
}

export interface Product {
	id: string;
	name: string;
	description: string;
	original_price: number;
	price: number;
	stock: number;
	category: Category;
	tags: string[];
	manufacturer: Manufacturer;
	image_url: string;
}

export interface Products {
	count: number;
	products: Product[];
}

export const PRODUCTS_PACKAGE_NAME = 'products';

export interface ProductsServiceClient {
	create(request: CreateProductDto): Observable<Product>;

	findOne(request: FindOneProductDto): Observable<Product>;

	findAll(request: Empty): Observable<Products>;

	update(request: UpdateProductDto): Observable<Product>;

	remove(request: RemoveProductDto): Observable<Empty>;

	permanentlyRemove(request: PermanentlyRemoveProductDto): Observable<Empty>;
}

export interface ProductsServiceController {
	create(
		request: CreateProductDto,
	): Promise<Product> | Observable<Product> | Product;

	findOne(
		request: FindOneProductDto,
	): Promise<Product> | Observable<Product> | Product;

	findAll(request: Empty): Promise<Products> | Observable<Products> | Products;

	update(
		request: UpdateProductDto,
	): Promise<Product> | Observable<Product> | Product;

	remove(request: RemoveProductDto): Promise<Empty> | Observable<Empty> | Empty;

	permanentlyRemove(
		request: PermanentlyRemoveProductDto,
	): Promise<Empty> | Observable<Empty> | Empty;
}

export function ProductsServiceControllerMethods() {
	return function (constructor: Function) {
		const grpcMethods: string[] = [
			'create',
			'findOne',
			'findAll',
			'update',
			'remove',
			'permanentlyRemove',
		];
		for (const method of grpcMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcMethod('ProductsService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
		const grpcStreamMethods: string[] = [];
		for (const method of grpcStreamMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcStreamMethod('ProductsService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
	};
}

export const PRODUCTS_SERVICE_NAME = 'ProductsService';
