// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v3.20.3
// source: proto/users/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { UserLoginDto, UserLoginResponse } from './user-login.dto';
import { AdminLoginDto, AdminLoginResponse } from './admin-login.dto';
import { UserRegisterDto, UserRegisterResponse } from './user-register.dto';
import { User } from '../users';
import { VerifyEmailDto, VerifyEmailResponse } from './verify-email.dto';
import { ResetPasswordDto, ResetPasswordResponse } from './reset-password.dto';

export const protobufPackage = 'users';

export interface AuthenticateDto {
	Authentication: any;
}

export interface AuthenticateResponse {
	user: User;
}

export interface ConfirmVerifyEmailDto {
	token: string;
}

export interface ConfirmVerifyEmailResponse {
	message: string;
}

export interface ForgotPasswordDto {
	email: string;
}

export interface ForgotPasswordResponse {
	message: string;
}

export const USERS_PACKAGE_NAME = 'users';

export interface AuthServiceClient {
	login(request: UserLoginDto): Observable<UserLoginResponse>;

	adminLogin(request: AdminLoginDto): Observable<AdminLoginResponse>;

	register(request: UserRegisterDto): Observable<UserRegisterResponse>;

	authenticate(request: AuthenticateDto): Observable<AuthenticateResponse>;

	verifyEmail(request: VerifyEmailDto): Observable<VerifyEmailResponse>;

	confirmVerifyEmail(
		request: ConfirmVerifyEmailDto,
	): Observable<ConfirmVerifyEmailResponse>;

	forgotPassword(
		request: ForgotPasswordDto,
	): Observable<ForgotPasswordResponse>;

	resetPassword(request: ResetPasswordDto): Observable<ResetPasswordResponse>;
}

export interface AuthServiceController {
	login(
		request: UserLoginDto,
	):
		| Promise<UserLoginResponse>
		| Observable<UserLoginResponse>
		| UserLoginResponse;

	adminLogin(
		request: AdminLoginDto,
	):
		| Promise<AdminLoginResponse>
		| Observable<AdminLoginResponse>
		| AdminLoginResponse;

	register(
		request: UserRegisterDto,
	):
		| Promise<UserRegisterResponse>
		| Observable<UserRegisterResponse>
		| UserRegisterResponse;

	authenticate(
		request: AuthenticateDto,
	):
		| Promise<AuthenticateResponse>
		| Observable<AuthenticateResponse>
		| AuthenticateResponse;

	verifyEmail(
		request: VerifyEmailDto,
	):
		| Promise<VerifyEmailResponse>
		| Observable<VerifyEmailResponse>
		| VerifyEmailResponse;

	confirmVerifyEmail(
		request: ConfirmVerifyEmailDto,
	):
		| Promise<ConfirmVerifyEmailResponse>
		| Observable<ConfirmVerifyEmailResponse>
		| ConfirmVerifyEmailResponse;

	forgotPassword(
		request: ForgotPasswordDto,
	):
		| Promise<ForgotPasswordResponse>
		| Observable<ForgotPasswordResponse>
		| ForgotPasswordResponse;

	resetPassword(
		request: ResetPasswordDto,
	):
		| Promise<ResetPasswordResponse>
		| Observable<ResetPasswordResponse>
		| ResetPasswordResponse;
}

export function AuthServiceControllerMethods() {
	return function (constructor: Function) {
		const grpcMethods: string[] = [
			'login',
			'adminLogin',
			'register',
			'authenticate',
			'verifyEmail',
			'confirmVerifyEmail',
			'forgotPassword',
			'resetPassword',
		];
		for (const method of grpcMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcMethod('AuthService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
		const grpcStreamMethods: string[] = [];
		for (const method of grpcStreamMethods) {
			const descriptor: any = Reflect.getOwnPropertyDescriptor(
				constructor.prototype,
				method,
			);
			GrpcStreamMethod('AuthService', method)(
				constructor.prototype[method],
				method,
				descriptor,
			);
		}
	};
}

export const AUTH_SERVICE_NAME = 'AuthService';
