// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v3.20.3
// source: proto/common.proto

/* eslint-disable */

export const protobufPackage = 'common';

export interface Empty {}

export const COMMON_PACKAGE_NAME = 'common';
